src/builder-flatpak-utils.c
I was putting together a Fedora flatpak-builder package and ran into undefined flatpak_get_kernel_arch() on ppc64le. It's guarded by ifdefs which is why the build didn't break on x86_64. This adds back the accidentally lost function.
=> Add back accidentally lost flatpak_get_kernel_arch

doc/flatpak-builder.xml
`--default-branch` and `--bundle-sources` weren't documented.
Additionally, `--run` and `--show-deps` take a restricted set of options, which wasn't documented either.
=> Add missing documentation

configure.ac
Without the '[]', if the error sentence contains a comma(just as the line 46), it will cause strange output or error, such as:
configure: error: You need at least version 0.9.13 of flatpak
else your version is Flatpak 0.9.7
or other syntax error.
=> add the missing '[]' around AC_MSG_ERROR

src/builder-main.c
This is no longer xdg-app-builder, but flatpak-builder.
=> Change debug output from XAB to FB

src/builder-options.c
It may be the case that we've e.g. specified a custom metadata file that
has network access, so always disable it explicitly during the builds.
=> Always pass --unshare=network when building sandboxed

src/builder-cache.c, src/builder-cache.h, src/builder-main.c
A commonly used CI workflow is to chain the following steps:
> flatpak-builder --stop-at=<module>
> flatpak build <commands to build module from local checkout>
> flatpak-builder --finish-only
Unfortunately, the last step always purge all the compilation cache
created by the first one. All build steps are marked unused by default
and since they are skipped due to the option --finish-only, all of them
are always pruned by the gc function.
As a result, flatpak-builder cache becomes useless, a full compilation
is always performed.
Improve this by not cleaning unused stages when no compilation is done
by flatpak-builder (i.e: when flatpak-builder is used with --export-only
or --finish-only option).
See also: https://gitlab.gnome.org/GNOME/Initiatives/wikis/DevOps-with-Flatpak
=> Don't prune build stages from cache with --{export,finish}-only

doc/flatpak-manifest.xml
It wasn't obvious to me what a command was - whether it was run through a shell or separated into an argument list to be invoked directly. Looking at [the source code](https://github.com/flatpak/flatpak-builder/blob/85eb2f1a644506946eb82a4b797a2d687d747d41/src/builder-module.c#L1745-L1751) shows that each command is run by a shell.
=> Expand on what a command is for simple buildsystem

doc/flatpak-manifest.xml, src/builder-source-archive.c
This allows you to override the base-name, which affects how the
file is uncompressed.
Fixes https://github.com/flatpak/flatpak-builder/issues/158
=> archive source: Add dest-filename support

src/builder-manifest.c
The prompts don't currently work when we shell out to
flatpak, so this is broken without -y.
=> install-deps: Always pass -y when installing

src/builder-main.c
These days flatpak install will always prompt for input,
so we pass -y to it because otherwise (due to non-inherited
stdin) we auto-answer no.
Fixes https://github.com/flatpak/flatpak-builder/issues/170
=> Fix --install with latest flatpak by passing -y

doc/flatpak-manifest.xml, src/builder-source-archive.c, src/builder-source-patch.c
When applying patches using git, git apply will ignore non-existent
patches that apply to non-existent files. As the vanilla source we use
to apply those patches might not be a git tree (eg. a tarball), make
sure that the tree is initialised before apply those git patches.
Fixes "Skipped patch ..." messages appearing in builds.
=> builder: Initialise git tree when using "use-git" for patches

doc/flatpak-manifest.xml
The description for "dest-filename" was copy/pasted from the "file"
source's documentation for the same property. The default filename is
actually autogen.sh
=> docs: Fix default value for script source's "dest-filename"

src/builder-flatpak-utils.h, src/builder-utils.c
If we are spawning applications on the host using the Development service,
then we want those commands to exit when the flatpak-builder process
exits, as can happen from Ctrl^C or kill().
=> utils: force exit host commands when flatpak-builder exits

doc/flatpak-builder.xml, doc/flatpak-manifest.xml, src/builder-main.c, src/builder-manifest.c, src/builder-manifest.h, tests/test.json, tests/test.yaml
Provide a --token-type command line option and a token-type manifest
property that allows passing the token type to build-export. The
manifest property takes precendence over the CLI option. In either case,
the value will be passed to build-export if it's >= 0. This requires
flatpak >= 1.6 to use the --token-type option in build-export.
=> Support passing --token-type to build-export

src/builder-source-bzr.c
Bazaar-NG (bzr) relies on Python 2, which has reached end-of-life, and
appears to be essentially unmaintained itself. Try using Breezy (brz),
a "friendly fork" of bzr that has been ported to Python 3 and is
maintained.
=> bzr: Run brz in preference to bzr

src/builder-options.c
=> Fix `run-tests` with `--sandbox` and empty `test-args`

src/builder-cache.c
When the cache is broken, the variant from ostree is not
a reliable source of information. The variant may thus fail to
be extracted.
I had a crash after my btrfs decided to mess up my filesystem:
```
gdb --args flatpak-builder --install --user --install-deps-from=flathub  --ccache --keep-build-dirs  --force-clean -v  --repo=/var/tmp/fb.repo fpbuilder org.signal.Signal2.json 
GNU gdb (Ubuntu 8.1-0ubuntu3.2) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show …
```
=> cache: sanity check the subject in builder_cache_lookup

src/builder-manifest.c
Order options before positional arguments when installing dependencies.
This makes no functional difference as far as I know but it looks
cleaner.
=> Fix ordering in "flatpak install" command

src/builder-manifest.c
An app may use `--metadata` in the `finish-args` section to
add section/key/value entries in the metadata file.
If we pass this through to `flatpak build`, it's interpreted to
be a filename. Since it's not a filename, this leads to the
metadata file not being found, and an error is raised like this:
/home/sam/src/gnome-photos/.flatpak-builder/rofiles/rofiles-qtBvVQ not initialized, use flatpak build-init
=> Ignore the `--metadata` argument of flatpak build-finish

src/builder-git.c, src/builder-git.h, src/builder-main.c, src/builder-source-git.c
Pass `_MIRROR_SUBMODULES` flag to `builder_git_checkout()`, so that we don't try to extract submodules if they the were disabled.
It's entirely possible that I've got everything wrong, but this seems to work.
Fixes #337
=> Don't extract git submodules if not mirrored

src/builder-context.c, src/builder-flatpak-utils.c
The actual command for unmounting the rofs was not printed, as opposed
to the command to mount the fs. The format of the message is also
normalized for easier debugging.
@alexlarsson thx for reviewing!
=> Normalize rofiles-fuse related logs.

src/builder-git.c, src/builder-git.h, src/builder-source-git.c
Bug was found by @lionirdeadman due to being hit with some bizarre Flathub build errors.
=> source-git: Don't bundle submodules if disabled

.gitmodules, Makefile.am, autogen.sh
* autogen.sh: Remove remnants of bundled copy of bubblewrap
* Move libglnx submodule into subprojects/
This is a step towards being able to build using Meson rather than
Autotools (#382). Meson has built-in support for subprojects, but requires
them to appear in the top-level subprojects/ directory.
We have to add -Isubprojects because we include <libglnx/libglnx.h>.
=> Move libglnx submodule into subprojects/

src/builder-main.c
When `add-extension` entry with `bundle: true` explicitly specifies `version`, export the extension under this branch, instead of always using parent app branch.
Fixes #388
=> Make bundled extension branch selectable

autogen.sh, configure.ac
* autogen.sh: Remove remnants of bundled copy of bubblewrap
* build: Remove obsolete check for fdwalk
Maybe Flatpak calls this, but flatpak-builder doesn't.
* build: Remove obsolete check for sys/capability.h
Nothing in flatpak-builder or libglnx needs this.
* build: Remove instructions for maintaining libtool interface versioning
flatpak-builder doesn't have a shared library.
* build: Comment why we check for <sys/xattr.h>
=> Clean up dead code in build system

src/builder-context.c, src/builder-context.h, src/builder-flatpak-utils.c, src/builder-flatpak-utils.h, src/builder-source-archive.c, src/builder-source-bzr.c, src/builder-source-dir.c, src/builder-source-extra-data.c, src/builder-source-file.c, src/builder-source-git.c, src/builder-source-patch.c, src/builder-source-script.c, src/builder-source-shell.c, src/builder-source-svn.c, src/builder-source.c, src/builder-source.h, src/builder-utils.c
Don't allow builds to create files outside the build dir, and, if sandboxed, read files outside the manifest base dir.
=> Validate paths

doc/flatpak-manifest.xml, src/builder-flatpak-utils.c, src/builder-flatpak-utils.h, src/builder-main.c, src/builder-manifest.c, src/builder-module.c, src/builder-options.c, src/builder-options.h, src/builder-source-archive.c, src/builder-source-patch.c, src/builder-source-shell.c, src/builder-utils.c, src/builder-utils.h
Meant to replace #406 
Some applications have security tokens passed by their build system. In these cases, this option allow their use without distributing them in the bundle.
This PR add the new option `secret-opts` and `secret-env`.
The first is meant to be used with build system like cmake and meson, the last is meant to be used with 'build-command' and 'post-install'.
The builder check for `secret-opts` with a `$`+"env var name" showing which host env var shall replace it. The builder will replace them on the fly.
If the env var doesn't exist or the `$` is missing, the option will be ignored.
With this way, the bundle still contain the manifest and even show that this bundle have secrets.
It's mainly meant to be used with CI like github actions or gitlab CI/CD secret's.
This is the …
=> Add 'secret-opts' option to manifest

doc/flatpak-manifest.xml, src/Makefile.am.inc, src/builder-source-archive.c, src/builder-source-file.c, src/builder-source-inline.c, src/builder-source-inline.h, src/builder-source-script.c, src/builder-source.c
In some cases the user may need to embed small files into the manifest. This is especially common practice for automatic manifest generators, namely flatpak-builder-tools. Currently, inline data can be stored as a `file` type source with `data:` URL.
This adds a specialized source type that writes given text content to a file (optionally, non-text data can be base64-encoded).
It provides an alternative to `data:` URLs, with following advantages:
- Less overhead from character escaping, thus, smaller manifest size. For yaml, overhead is reduced to none. For json, only a few special characters needs to be escaped.
- Much easier to write by hand (and read by a human), especially for yaml. For example, an embedded `.yarnrc` can be turned from this
```yaml
type: file
url: …
```
=> Add inline data source

src/builder-post-process.c
g_print() does not add its own newline. Building
org.learningequality.Kolibri, for example, produces an illegible
4096-character line. (4096 is just a coincidence AFAICT.)
I could not find other instances in this codebase where g_print() needs
a newline but does not have one.
=> post-process: Add missing newlines to Python cleanup

.github/ISSUE_TEMPLATE/bug_template.yml
Sorry for the second MR, I just noticed that it's inconsistent:
In the meantime I just made the R lower case, but if you prefer upper case, then I'll change this one back to how it was and make the R in "Feature request" capital.
=> Fix casing

configure.ac, doc/flatpak-builder.xml, doc/flatpak-manifest.xml
All of these DocBook 4 versions are compatible so let’s just use the latest one.
DocBook 5 would require changes.
=> doc: Unify on single DocBook version

src/builder-source-archive.c
This fix for not needing to manually set `archive-type: 7z` on 7zip archive souce.  
related: https://github.com/flatpak/flatpak-builder/pull/323
=> source-archive: Fix get_type on 7zip archive

src/builder-post-process.c
Fixes #429
Signed-off-by: Ryan Gonzalez <ryan.gonzalez@collabora.com>
=> Avoid re-processing debug info from previous modules

data/flatpak-manifest.schema.json
Recognize the `have-kernel-module-*` condition added in flatpak/flatpak#4647
=> json-schema: Handle have-kernel-module- condition

src/builder-git.c, src/builder-git.h, src/builder-main.c, src/builder-source-git.c
Many projects are starting to change their default branch
name from 'master' to 'main' and similar, eg.:
https://gitlab.gnome.org/GNOME/evince/-/issues/1635
So when a project is not providing a specific branch,
instead of defaulting to 'master' we should ask the
remote repo which is their default branch name.
That can be retrieve with following command:
git ls-remote --symref origin HEAD
where 'origin' can also be a URL to the repository.
Fixes issue #375
=> ask for default branch name instead of harcoding 'master'

README.md
I noticed that the Link to Icon in the Readme no longer works.
=> Fix Link to Image in Readme

src/builder-context.c, src/builder-context.h, src/builder-main.c, src/builder-manifest.c
`flatpak-builder` overrides `SOURCE_DATE_EPOCH` with the last modification time of the manifest file (of the program being built).
With this option, it would provide a more convenient interface to perform the same thing, useful when trying to reproduce a build.
Concretely I just added an optional parameter `--override-source-date-epoch` which, if set, will override the `SOURCE_DATE_EPOCH` with the given value. 
It's my first time looking at the code of this project, therefore, even though I made minimal changes, I might have made some mistakes.
Update:
I also added the timestamp to the resolved manifest, to actually have reproducible builds.
=> Add option to override SOURCE_DATE_EPOCH.

src/builder-git.c
git 2.38.1 prevent file protocol to be used by default for security reasons. Such issue does not apply to flatpak-builder since the repos are overriden with local repo on purpose.
Fixes #495
Signed-off-by: Weng Xuetian <wengxt@gmail.com>
=> Allow use file protocol when update submodule.

data/flatpak-manifest.schema.json
According to "test-commands"' description: "Array of commands to run during the tests.", it's value type should be an array of strings.
=> json-schema: Fix the "test-commands"' value type checking

src/builder-main.c, src/builder-utils.c
This MR fixes #492, a segfault when the manifest is empty.
The second commit fixes a segfault when the manifest contains only a number or a string.
Best Regards
Manuel
=> Fix segfaults

src/builder-main.c
When doing an initial clone of a repo to get the manifest from a git repo hosted by a HTTP (or HTTPS) server, shallow clones fail with the following message:
```
Initialized empty Git repository in /home/purism/.flatpak-builder/git/https_domain.com_code_repo.git-L04WW1/
Fetching git repo https://domain.com/code/repo.git, ref refs/heads/phil/flatpak
fatal: dumb http transport does not support shallow capabilities
Can't clone manifest repo: Child process exited with code 128
```
adding the `--no-shallow-clone` doesn't change the behavior for this `--from-git=` clone. This patch fixes the behavior and makes it work as exepected for me.
fixes #501
=> also disable shallow clone when retrieving manifest "from-git" with --from-git

src/builder-git.c
I found this bug with this repository:
https://github.com/GuitarML/SmartGuitarAmp
For the resulting flatpak manifest I had to skip submodules and add the sources.
See https://github.com/hfiguiere/flathub/blob/guitarml/org.freedesktop.LinuxAudio.Plugins.GuitarML.json#L231
So basically if git ls-tree return nothing when the submodule is list in gitmodule it will just be skipped. I check with my manifest and could successfully reenable the submodules.
=> git: Just skip submodules that git ls-tree don't know about

tests/Makefile.am.inc
* tests: Don't install buildutil/tap-driver.sh
This is not necessary for the "as-installed" tests, and happens to cause
lint warnings from Debian's Lintian tool.
* tests: Install all deprecation tests when installed-tests are enabled
Resolves: #511
=> Fix installation of "as-installed" tests

data/flatpak-manifest.schema.json, src/builder-utils.c
This is used by various tools to specify a JSON schema.
Fixes #515
=> Ignore $schema properties in manifests

doc/flatpak-manifest.xml
It's not clear from the docs that `config-opts` is used for the cmake buildsystem as well as autotools.
=> Document that config-opts is used for CMake

.github/workflows/check.yml, .gitignore, Makefile.am, README.md, doc/meson.build, meson.build, meson_options.txt, src/builder-cache.c, src/builder-cache.h, src/builder-extension.c, src/builder-flatpak-utils.c, src/builder-flatpak-utils.h, src/builder-main.c, src/builder-manifest.c, src/builder-module.c, src/builder-post-process.c, src/meson.build, subprojects/libglnx.wrap, subprojects/libyaml.wrap, tests/meson.build
So I started a meson port, which compiles and runs fine. But before I proceed to finish completely the port I have a few questions first.
1. Would a meson port be acceptable?
2. Should I drop the autotools buildsystem to avoid having them deviate in quality as time passes?
3. The main reason I want to port flatpak-builder to meson is because I'd like to make flatpak-builder available too as a library that GNOME Builder could use to avoid all the duplication that happens between both codebases. That *could* be done with autotools, but I really don't want nor know how to write autoconf stuff. That would allow GNOME Builder to do a more fine grained treatment on the modules and sources of a manifest, like updating modules A, B, and E but not *all* modules, as we've been willing to do in …
=> Port to meson

Makefile.am
* build: Distribute Meson build files for libglnx subproject
Resolves: https://github.com/flatpak/flatpak-builder/issues/530
* build: During distcheck, verify that all required Meson files are included
Reproduces: https://github.com/flatpak/flatpak-builder/issues/530
cc @amigadave
=> build: Distribute Meson build files for libglnx subproject

Makefile.am, meson_options.txt, tests/meson.build, tests/tap.test.in, tests/test-keyring/meson.build, tests/test-keyring2/meson.build
* tests: Run each test in a new, empty directory
The test framework in libtest.sh expects this, and it's what the
Autotools build system did.
* tests: Run in parallel
Now that each test has its own working directory, hopefully we can run
them in parallel.
* tests: Add GNOME-style installed tests to Meson build
This was supported with Autotools, but missing from Meson until now.
Resolves: https://github.com/flatpak/flatpak-builder/issues/528
=> meson: Reinstate parallel tests, add as-installed testing

Makefile.am
* build: Distribute tap.test.in in tarball releases
Resolves: https://github.com/flatpak/flatpak-builder/issues/534
* build: Enable installed-tests when testing Meson build
Reproduces: https://github.com/flatpak/flatpak-builder/issues/534
=> Fix Meson build from Autotools dist (again)

src/meson.build
This had two issues in the Meson build system: it was always set to true even if configured with `-Dyaml=disabled`, and the `#ifdef FLATPAK_BUILDER_ENABLE_YAML` check always succeeded because `set10` defines the macro to 1 or 0. Use `set` with a boolean value instead, which defines or undefines the macro, leading to the same interface as in Autotools.
---
This is not hugely important, I don't know whether anyone actually disables YAML in practice - it's an extra dependency, but YAML is so much nicer as a human-written format than JSON.
The other possibility here would be to remove the option, and say that 1.3.x/1.4.x unconditionally supports YAML manifests.
=> build: Fix Meson build when yaml is disabled

tests/libtest.sh, tests/meson.build, tests/test-builder-deprecated.sh, tests/test-builder-python.sh, tests/test-builder.sh
* tests: Send diagnostic output from Flatpak etc. to stderr
This avoids interfering with the machine-readable TAP output on stdout,
which should be interpreted by Meson.
* tests: Turn an unstructured "echo" into a TAP diagnostic[
* tests: Tell Meson to parse TAP output
Resolves: https://github.com/flatpak/flatpak-builder/issues/529
---
I haven't really tested `test-builder-python.sh` since my distribution no longer supports Python 2, but I think it's right.
=> Use TAP for Meson tests

data/flatpak-manifest.schema.json
To avoid displaying the entire schema URL.
https://github.com/SchemaStore/schemastore/blob/master/editor-features.md#title-as-an-expected-object-type
=> improve editor experience by adding a `title`

data/flatpak-manifest.schema.json
#408 was merged before the schema was added (#432) but the new options were never added to the schema.
=> json-schema: Add "secret-env" and "secret-opts"

data/flatpak-manifest.schema.json
Add missing "secret-opts", I didn't realized that `"config-opts"` was defined two times while I made #543.
I'm sorry for not noticing that.
=> json-schema: Fix missing "secret-opts"

src/builder-git.c
Without this patch https://github.com/nidefawl/daw-deps/blob/master/.gitmodules is not parsed properly causing `tinyspline` to never be checked out because it check for `tinyspline` since there is a whitespace at the end of the `path = `.
=> builder-git: trim whitespace from submodule path

.github/workflows/check.yml, .gitignore, ci/build.sh, configure.ac, doc/flatpak-manifest.xml, meson.build, src/builder-context.c, src/builder-context.h, src/builder-main.c, src/builder-manifest.c
This the completed port to libappstream with a counterpart on the flatpak side(https://github.com/flatpak/flatpak/pull/5277). It is based of off @pwithnall and @barthalion previous work. 
Reasoning has been taken from @pwithnall's original pr
> appstream-glib is mostly unmaintained, and appstream is more
actively developed (and up to date with the AppStream specification).
> This ports flatpak-builder to use the command line tools from appstream
(appstreamcli and appstreamcli-compose) rather than the ones from
appstream-glib (appstream-util, appstream-builder and
appstream-compose).
> This should result in no changes for most things, but should fix
propagation of \<requires>/\<recommends> elements, screenshot
>\<caption>s, and other elements which have been added to the AppStream …
=> Port to libappstream

src/builder-cache.c
See https://github.com/ostreedev/ostree/pull/2874
"commit: fix ostree deployment on 64-bit inode fs"
=> builder: Fix silent truncation of >32 bit inodes

src/builder-module.c
Running just `meson` is deprecated and should be replaced with the explicit `meson setup` ([Reference](https://mesonbuild.com/Commands.html#setup))
=> builder-module: Use `meson setup` instead of `meson`

.github/workflows/check.yml
This PR bumps the actions/checkout version from v3 (Node 16), v2 and v1 to v4 (Node 20) as Node 16 is reaching eol soon and older versions have reached eol.
Ref. https://nodejs.org/en/blog/announcements/nodejs16-eol
=> CI: bump actions/checkout to v4

src/builder-manifest.c
The --components switch for specifying allowed IDs is stricter and will refuse to process historically correct values.
=> Tell libappstream to accept IDs with ".desktop" suffix

src/builder-source-file.c
first_error is never used and doesn't seem needed.
=> Fix propagating invalid error

src/builder-flatpak-utils.c
This will abort the download if it’s slower than 10KB/sec for 60 seconds with CURLE_OPERATION_TIMEDOUT
The limits are copied from https://github.com/flatpak/flatpak/commit/d6b10c26efd583805ec7085c040a52d0884c305b
This seems it could be useful in CI which may want to proactively kill a pipeline if a download timeouts
I have no idea how to test this, but hopefully it works.
@nanonyme wanted this for Freedesktop SDK CI
=> Set a download speed timeout in the curl session

src/builder-utils.c
With this option set, curl will automatically accept and decompress all compressed content types it supports (as of today, brotli, gzip and deflate). Currently, if the website refuses to offer a non-compressed request, flatpak-builder will simply not be able to download it (usually downloading a 403 forbidden page or something).
This is analogous to the `--compressed` flag on the CLI and, as far as I'm concerned, will have no drawback (web servers just ignore it if they don't want to serve compressed files, it is an option and not a request) so I didn't add a configuration key to toggle.
=> Enable compressed downloads for file sources

doc/flatpak-manifest.xml
This was soft deprecated in https://github.com/flatpak/flatpak-builder/commit/3341fb08adc981879043445e8c40883786705738#diff-fe51491bafa983ec48ccdaa2da758238ee9d5623e20cea285cae410d22dd645dR73, https://github.com/flatpak/flatpak-builder/commit/3341fb08adc981879043445e8c40883786705738#diff-fe51491bafa983ec48ccdaa2da758238ee9d5623e20cea285cae410d22dd645dR359-R365 in favour of "id" which aligns with appstream https://github.com/ximion/appstream/commit/8b412031037ea08028279e9408ea0eda01938c48
This achieves nothing other than putting some doubt and confusion to rest in flathub when people open PRs to switch appid -> id and the docs have no mention of it anywhere.
As far as I can tell, this is the primary source and the only place app-id/id is mentioned in the context of a manifest. There are …
=> Add a note that app-id is deprecated

doc/flatpak-manifest.xml, src/builder-extension.c, src/builder-flatpak-utils.h
This is an existing flatpak feature that was never added to flatpak-builder, so it couldn't be used in app manifests.
I've simply duplicated the code for `enable-if` and changed the name. That was enough to get `autoprune-unless` to pass through from the manifest to the app metadata.
To help address https://github.com/flatpak/flatpak/issues/2718, I looked into why `flatpak uninstall --unused` removes 64bit nvidia drivers, but not 32bit. I discovered that the `org.freedesktop.Platform.GL` extension point was defined with `autoprune-unless=active-gl-driver`, but `org.freedesktop.Platform.GL32` was not, and that the latter is defined in each app that requires it, rather than in the runtime.
With this in place, as long as all apps that define the extension point use …
=> Add support for 'autoprune-unless' for extensions

doc/flatpak-manifest.xml, src/builder-manifest.c, tests/Hello-desktop.appdata.xml, tests/Hello.appdata.xml, tests/Hello.desktop, tests/org.test.Hello.appdata.xml, tests/org.test.Hello.desktop, tests/test-builder.sh, tests/test-rename-appdata.json, tests/test-rename.json, tests/test.json, tests/test.yaml
It include more testing
Close #90
=> manifest: Properly change the app id in the appstream file

src/builder-manifest.c
Followup from https://github.com/flatpak/flatpak-builder/pull/579
=> manifest: Don't emit empty id in `provides` when renaming

src/builder-module.c, tests/test-configure, tests/test-rename-appdata.json, tests/test-rename.json, tests/test.json, tests/test.yaml
flatpak-builder relies on patched cmake and meson from
freedesktop-sdk to change libdir from lib64 to lib on 64bit
distributions. This dependency is *weird* since it's actually
flatpak that sets up the dynamic linker paths. Instead, put
responsibility for setting up correct libdir to flatpak-builder
always.
=> Always calculate libdir

src/builder-module.c
Fixes 8c036e00630e35423c03388aacc06cd00dda74ea
It is being set to `$prefix/lib` but CMAKE_INSTALL_LIBDIR is not an absolute path by convention [1]:
> It should be a path relative to the installation prefix
When it is set to `/app/lib`, it is causing issues in applications [2]
[1]: https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html#result-variables
[2]: https://github.com/flathub/io.github.martinrotter.rssguard/issues/73#issuecomment-2208189029
=> builder-module: Fix cmake libdir value

src/builder-main.c
Tested building an SDK+Runtime and a Runtime without custom Sdk (thus no platform-id)
Fixes: #630
=> builder-main: install platform as well as sdk if both are built

.github/workflows/check.yml
This tries to upgrade firefox to a snap package and wastes time downloading MBs...
https://github.com/flatpak/flatpak-builder/actions/runs/17385865788/job/49352696434?pr=655#step:2:142
=> ci: Don't run apt upgrade

.github/workflows/check.yml, README.md, ci/libbuild.sh, src/builder-source-archive.c
info-zip's unzip is unmaintained and horribly behind security patches so switch to bsdunzip from libarchive.
See https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/blob/687b07205c02d28622053d419ec0f3c6f0240f5b/elements/components/unzip.bst#L45-68 and https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1777
=> builder-source-archive: Switch to bsdunzip

doc/flatpak-builder.xml, src/builder-main.c, tests/Makefile.am.inc, tests/meson.build, tests/org.flatpak_builder.gui.desktop, tests/org.flatpak_builder.gui.json, tests/org.flatpak_builder.gui.metainfo.xml, tests/test-builder.sh
```
This is needed to store the application icons and the mirrored
screenshots (as done by appstream) to the ostree repo. This can be
useful in many ways, the primary being flat-manager extracts [1] these
screenshot refs and stores them in the server so that application
store frontends can use their own mirrored screenshot and icon URLs.
This has been for the longest time done at various downstream levels
such as in buildbot [2], flatpak-github-actions [3] and vorarbeiter [4]
(the successor to buildbot) but it's more user friendly to have
flatpak-builder do this extra work.
[1]: https://github.com/flatpak/flat-manager/commit/eff43004756c011b0a0d034a61cec84836b8e0a9
[2]: https://github.com/flathub-infra/buildbot/blob/9d8e2b5483b2e446389548446ebf9c3934380682/master/buildbot/flathub_master.py …
```
=> builder-main: Commit mirrored media as screenshot ref to exported repo

src/builder-source-patch.c
Patches applied with `git am` require committing. If `git` is configured to require signing for commits, then this will block flatpak-builder. The argument overrides `commit.gpgsign=true`. (`git config --global commit.gpgsign true`)
I have not tested this myself. Is it possible to test this on an existing set-up?
=> git-am: add --no-gpg-sign to override config

.github/workflows/check.yml, tests/meson.build
Copy pasted the wrong thing between makefile and meson.
=> tests: Fix incorrect paths for test files

src/builder-manifest.c
Fixes https://github.com/flatpak/flatpak-builder/issues/341
=> builder-manifest: Log sdk, runtime and base versions and commits used

src/builder-main.c
This creates or updates the appstream and appstream2 refs to the exported repo. The appstream refs are needed to display appstream information (version, name etc.) if the exported repo is being used as a remote.
If `files/share/app-info` does not exist inside the build for example for extensions etc. flatpak build-export simply continues by printing a line.
Fixes https://github.com/flatpak/flatpak-builder/issues/376
=> builder-main: Always update appstream branches when exporting to repo

tests/org.flatpak_builder.gui.json, tests/test-builder.sh
This makes it harder for me to write the test for https://github.com/flatpak/flatpak-builder/pull/652, but if offline tests are wanted, so be it.
I didn't delete the test files, as I plan to reuse them later for the test in #652. I need some fully qualified and valid desktop file, metainfo file for that.
=> tests: Allow screenshot ref commit test to run offline

src/builder-manifest.c
Fixes 7a710f6cc5b6e27a5c0a0eff376bbaccfe46c097
```
In file included from /usr/include/glib-2.0/glib.h:117,
from /usr/include/glib-2.0/glib/gi18n.h:23,
from ../src/builder-manifest.c:31:
In function ‘g_autoptr_cleanup_generic_gfree’,
inlined from ‘_rename_icon’ at ../src/builder-manifest.c:2346:28:
/usr/include/glib-2.0/glib/glib-autocleanups.h:32:3: warning: ‘new_name’ may be used uninitialized [-Wmaybe-uninitialized]
32 |   g_free (*pp);
|   ^~~~~~~~~~~~
../src/builder-manifest.c: In function ‘_rename_icon’:
../src/builder-manifest.c:2346:28: note: ‘new_name’ was declared here
2346 |           g_autofree char *new_name;
|                            ^~~~~~~~
```
=> builder-manifest: Fix an uninitialised variable warning
